[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.39.10",
    "gspread>=6.2.1",
    "oauth2client>=4.1.3",
    "pandas>=2.3.1",
    "pillow>=11.3.0",
    "streamlit>=1.46.1",
]
